use std::fmt::Write;

use crate::pr_quality::GitHubUser;

/// Metrics for a contributor reputation report.
pub struct ContributorMetrics {
    pub login: String,
    pub account_age_days: u32,
    pub profile_signals: u32,
    pub public_repos: u32,
    pub followers: u32,
    pub global_merge_ratio: Option<f64>,
    pub is_new_account: bool,
}

impl ContributorMetrics {
    pub fn from_user(user: &GitHubUser, merge_ratio: Option<f64>, min_age_days: u32) -> Self {
        let age = user.account_age_days();
        Self {
            login: user.login.clone(),
            account_age_days: age,
            profile_signals: user.profile_signal_count(),
            public_repos: user.public_repos,
            followers: user.followers,
            global_merge_ratio: merge_ratio,
            is_new_account: age < min_age_days,
        }
    }
}

/// Format the contributor report as a Check Run summary (always `neutral` conclusion).
pub fn format_contributor_report(m: &ContributorMetrics) -> (String, String, String) {
    let conclusion = "neutral".to_string();
    let title = format!("Contributor Report: @{}", m.login);

    let mut summary = format!(
        "## Contributor Report: @{}\n\n\
         | Metric | Value |\n\
         |--------|-------|\n",
        m.login
    );

    let _ = writeln!(summary, "| Account age | {} days |", m.account_age_days);
    let _ = writeln!(
        summary,
        "| Profile completeness | {}/7 signals |",
        m.profile_signals
    );
    let _ = writeln!(summary, "| Public repos | {} |", m.public_repos);
    let _ = writeln!(summary, "| Followers | {} |", m.followers);

    if let Some(ratio) = m.global_merge_ratio {
        let _ = writeln!(summary, "| Global PR merge rate | {:.0}% |", ratio * 100.0);
    } else {
        let _ = writeln!(summary, "| Global PR merge rate | N/A (no closed PRs) |");
    }

    if m.is_new_account {
        summary.push_str("\n> ⚠️ **New account** — additional review recommended.\n");
    }

    summary.push_str(
        "\n> This report is informational and does not block the PR. \
         Generated by [metsuke](https://github.com/plenoai/metsuke).",
    );

    (conclusion, title, summary)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_metrics() -> ContributorMetrics {
        ContributorMetrics {
            login: "testuser".into(),
            account_age_days: 365,
            profile_signals: 5,
            public_repos: 20,
            followers: 10,
            global_merge_ratio: Some(0.75),
            is_new_account: false,
        }
    }

    #[test]
    fn report_is_neutral() {
        let (conclusion, _, _) = format_contributor_report(&sample_metrics());
        assert_eq!(conclusion, "neutral");
    }

    #[test]
    fn new_account_warning() {
        let mut m = sample_metrics();
        m.is_new_account = true;
        let (_, _, summary) = format_contributor_report(&m);
        assert!(summary.contains("New account"));
    }

    #[test]
    fn no_merge_history() {
        let mut m = sample_metrics();
        m.global_merge_ratio = None;
        let (_, _, summary) = format_contributor_report(&m);
        assert!(summary.contains("N/A"));
    }
}
